export const TRANSACTION_LIST_TABLE_SETTING_DATA = [
  {
    name: "Hesab",
    dataIndex: "cashboxName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İcra tarixi",
    dataIndex: "createdAt",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməliyyat tarixi",
    dataIndex: "dateOfTransaction",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Sənəd",
    dataIndex: "documentNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Növ",
    dataIndex: "operationDirectionId",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "categoryName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Alt kateqoriya",
    dataIndex: "subCategoryName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qarşı tərəf",
    dataIndex: "contactOrEmployee",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Xərc Mərkəzi",
    dataIndex: "paymentInvoiceInvoiceNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məbləğ",
    dataIndex: "amount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əsas valyuta",
    dataIndex: "amountConvertedToMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Biznes blok",
    dataIndex: "businessUnitId",
    standart: true,
    visible: true,
    fixed: false,
  },

  {
    name: "Status",
    dataIndex: "status",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məsul şəxs",
    dataIndex: "createdByName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ödəniş növü",
    dataIndex: "paymentTypeName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
];

export const FINANCE_OPERATIONS_SIDEBAR_SETTINGS = [
  {
    id: 1,
    name: "Biznes blok",
    dataIndex: "businessUnitIds",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 2,
    name: "Qarşı tərəf",
    dataIndex: "contacts",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 3,
    name: "Əməkdaş",
    dataIndex: "employees",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 4,
    name: "Hesab növü",
    dataIndex: "cashboxTypeIds",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 5,
    name: "Hesab",
    dataIndex: "cashboxes",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 6,
    name: "Əməliyyatın növü",
    dataIndex: "typeOfOperations",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 7,
    name: "Əməliyyat tarixi",
    dataIndex: "datetimeOfTransactionStart",
    dataIndexFrom: "datetimeOfTransactionEnd",
    standart: true,
    visible: true,
    fixed: false,
    multipleVal: true,
    fromValue: "",
    fromTo: "",
  },
  {
    id: 8,
    name: "Ödəniş təyinatı",
    dataIndex: "transactionTypes",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 9,
    name: "Kateqoriya",
    dataIndex: "transactionCatalogs",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 10,
    name: "Alt kateqoriya",
    dataIndex: "transactionItems",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 11,
    name: "Qaimə",
    dataIndex: "relatedInvoices",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 12,
    name: "Sənəd",
    dataIndex: "serialNumber",
    standart: true,
    visible: true,
    fixed: false,
    value: "",
  },
  {
    id: 13,
    name: "Ödəniş növü",
    dataIndex: "paymentTypes",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 14,
    name: "Əməliyyatçı",
    dataIndex: "createdByIds",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 15,
    name: "Baş əlaqə",
    dataIndex: "headContacts",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 16,
    name: "Əlaqə meneceri",
    dataIndex: "contactManagers",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 17,
    name: "Status",
    dataIndex: "isDeleted",
    standart: true,
    visible: true,
    fixed: false,
    value: undefined,
  },
  {
    id: 18,
    name: "Etiket",
    dataIndex: "parentLabels",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 19,
    name: "Alt etiket",
    dataIndex: "labels",
    standart: true,
    visible: true,
    fixed: false,
    value: [],
  },
  {
    id: 20,
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: true,
    visible: true,
    fixed: false,
    value: "",
  },
];

export const FinanceAdvanceReportsSettingData = [
  {
    name: "Sənəd",
    dataIndex: "documentNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Tarix",
    dataIndex: "dateOfTransaction",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Avans növü",
    dataIndex: "transactionType",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "categoryName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Alt kateqoriya",
    dataIndex: "subCategoryName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Hesab",
    dataIndex: "cashboxName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Mədaxil",
    dataIndex: "amountIn",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məxaric",
    dataIndex: "amountOut",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödəniş növü",
    dataIndex: "paymentTypeName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const FinanceAvanceEmployeSetingData = [
  {
    name: "Sənəd",
    dataIndex: "documentNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Tarix",
    dataIndex: "dateOfTransaction",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "categoryName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Alt kateqoriya",
    dataIndex: "subCategoryName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Hesab",
    dataIndex: "cashboxName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Mədaxil",
    dataIndex: "amountIn",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məxaric",
    dataIndex: "amountOut",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödəniş növü",
    dataIndex: "paymentTypeName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: true,
    visible: true,
    fixed: false,
  },
];
export const EMPLOYEE_BONUS_TABLE_SETTING_DATA = [
  {
    name: "Əməkdaş",
    dataIndex: "name",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Satış dövriyyəsi",
    dataIndex: "saleBonusTurnover",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Bonus növü",
    dataIndex: "saleBonusConfigurationId",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməkhaqqı valyutası",
    dataIndex: "currencyCode",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Hesablanmış bonus",
    dataIndex: "bonusAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Təyin edilmiş",
    dataIndex: "editedBonusAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməkhaqqıya tətbiq olunub",
    dataIndex: "applyToSalary",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];
export const RECEIVABLES_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "contactFullName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ödəniş tarixi",
    dataIndex: "firstOpenCreditDate",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Toplam Borclar",
    dataIndex: "invoiceDebtAmount",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ödənilib",
    dataIndex: "convertedPaidAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilib(%)",
    dataIndex: "paidInPercentage",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilməlidir",
    dataIndex: "amountToBePaid",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş",
    dataIndex: "lastPaymentAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş tarixi",
    dataIndex: "dateOfTransaction",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Günlərin sayı",
    dataIndex: "daysNum",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "type",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "categoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "headContactName",
    standart: false,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "phoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "emails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "idNumber",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Borc limiti",
    dataIndex: "debtLimit",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Borc limitin aşması",
    dataIndex: "debtLimitExceedingAmount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer",
    dataIndex: "manager",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "voen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "websites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "address",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "priceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməliyyat tarixi",
    dataIndex: "createdAt",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə olunub",
    dataIndex: "createdBy",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "officialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "generalDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "companyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "bankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "bankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "bankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "correspondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "settlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "swift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];
export const PAYABLES_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "contactFullName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ödəniş tarixi",
    dataIndex: "firstOpenCreditDate",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Toplam Borclar",
    dataIndex: "invoiceDebtAmount",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ödənilib",
    dataIndex: "convertedPaidAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilib(%)",
    dataIndex: "paidInPercentage",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilməlidir",
    dataIndex: "amountToBePaid",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş",
    dataIndex: "lastPaymentAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş tarixi",
    dataIndex: "dateOfTransaction",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Günlərin sayı",
    dataIndex: "daysNum",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "type",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "categoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "phoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "emails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "headContactName",
    standart: false,
    visible: true,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "idNumber",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Borc limiti",
    dataIndex: "debtLimit",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Borc limitin aşması",
    dataIndex: "debtLimitExceedingAmount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer",
    dataIndex: "manager",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "voen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "websites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "address",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "priceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməliyyat tarixi",
    dataIndex: "createdAt",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə olunub",
    dataIndex: "createdBy",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "officialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "generalDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "companyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "bankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "bankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "bankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "correspondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "settlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "swift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const VAT_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "contactFullName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Toplam Borc",
    dataIndex: "invoiceDebtAmount",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ödənilib",
    dataIndex: "convertedPaidAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilib(%)",
    dataIndex: "paidAmountPercentage",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilməlidir",
    dataIndex: "amountToBePaid",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş",
    dataIndex: "lastPaymentAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş tarixi",
    dataIndex: "dateOfTransaction",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Günlərin sayı",
    dataIndex: "daysNum",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "type",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "categoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "phoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "emails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "headContactName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "idNumber",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer",
    dataIndex: "manager",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "voen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "websites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "address",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "priceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməliyyat tarixi",
    dataIndex: "createdAt",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə olunub",
    dataIndex: "createdBy",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "officialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "generalDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "companyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "bankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "bankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "bankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "correspondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "settlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "swift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const ADVANCE_REPORTS_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "contactFullName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Məxaric",
    dataIndex: "amountCashOut",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Mədaxil",
    dataIndex: "amountCashIn",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Balans",
    dataIndex: "balance",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş",
    dataIndex: "lastTransactionAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş tarixi",
    dataIndex: "lastTransactionDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "contactType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "contactCategoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "contactPhoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "contactHeadContactName",
    standart: false,
    visible: true,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "contactEmails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer  (Əlaqə)",
    dataIndex: "contactManager",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "contactId",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "contactVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "contactWebsites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "contactAddress",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "contactPriceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat  (Əlaqə)",
    dataIndex: "contactDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "contactOfficialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "contactGeneralDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "contactCompanyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "contactBankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "contactBankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "contactBankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "contactCorrespondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "contactSettlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "contactSwift",
    standart: false,
    visible: false,
    fixed: false,
  },
];

export const EMPLOYEE_REPORTS_TABLE_SETTING_DATA = [
  {
    name: "Əməkdaş",
    dataIndex: "employeeName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Məxaric",
    dataIndex: "amountCashOut",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Mədaxil",
    dataIndex: "amountCashIn",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Balans",
    dataIndex: "balance",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş",
    dataIndex: "lastTransactionAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş tarixi",
    dataIndex: "lastTransactionDate",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const BALANCE_REPORTS_TABLE_SETTING_DATA = [
  {
    name: "Təsisçi",
    dataIndex: "tenantPersonName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Məxaric",
    dataIndex: "amountCashOut",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Mədaxil",
    dataIndex: "amountCashIn",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Balans",
    dataIndex: "balance",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş",
    dataIndex: "lastTransactionAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son ödəniş tarixi",
    dataIndex: "lastTransactionDate",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const CURRENCIES_REPORTS_TABLE_SETTING_DATA = [
  {
    name: "Başlama tarixi",
    dataIndex: "startAt",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Bitmə tarixi",
    dataIndex: "endAt",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Valyuta",
    dataIndex: "currencyCode",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Son məzənnə",
    dataIndex: "rate",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Əvvəlki məzənnə",
    dataIndex: "prevRate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dinamika (%)",
    dataIndex: "dynamicsPercent",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const PAYMENTTABLE_CREDITTABLE_TABLE_SETTING_DATA = [
  {
    name: "İcra tarixi",
    dataIndex: "createdAt",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qarşı tərəf",
    dataIndex: "contactName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Sənəd",
    dataIndex: "serialNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Kredit növü",
    dataIndex: "creditTypeName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kredit məbləği",
    dataIndex: "totalInvoiceAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilib",
    dataIndex: "totalPaidAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilib(%)",
    dataIndex: "totalPaidAmountPercentage",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənilməlidir",
    dataIndex: "remainingAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Aylıq ödəniş",
    dataIndex: "monthlyPaymentAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müddət (Ay)/dəfə",
    dataIndex: "numberOfMonths",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Status",
    dataIndex: "status",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "contactType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "contactCategoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "contactPhoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "contactEmails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer  (Əlaqə)",
    dataIndex: "contactManager",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "contactId",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "contactVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "contactWebsites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "contactAddress",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "contactPriceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat (Əlaqə)",
    dataIndex: "contactDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "contactOfficialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "contactGeneralDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "contactCompanyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "contactBankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "contactBankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "contactBankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "contactCorrespondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "contactSettlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "contactSwift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const PAYMENTTABLE_CREDITPAYMT_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "contactName",
    standart: true,
    visible: true,
    fixed: false,
  },

  {
    name: "Sənəd",
    dataIndex: "serialNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Kredit məbləği",
    dataIndex: "totalInvoiceAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Sənəd üzrə qalıq",
    dataIndex: "remainingAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödəniş məbləği",
    dataIndex: "monthlyPaymentAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödəniş tarixi",
    dataIndex: "date",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Status",
    dataIndex: "status",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Gecikmə (gün)",
    dataIndex: "latenessDays",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödənişlərin sayı",
    dataIndex: "numberOfMonths",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "contactType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "contactCategoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "contactPhoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "contactEmails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer (Əlaqə)",
    dataIndex: "contactManager",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "contactId",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "contactVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "contactWebsites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "contactAddress",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "contactPriceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat(Əlaqə)",
    dataIndex: "contactDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "contactOfficialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "contactGeneralDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "contactCompanyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "contactBankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "contactBankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "contactBankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "contactCorrespondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "contactSettlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "contactSwift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const FINANCE_CONSIGNMENT_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "client_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Verilmiş",
    dataIndex: "totalPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Geri alınmış",
    dataIndex: "returnedPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Satılmış",
    dataIndex: "soldPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qalan",
    dataIndex: "remainedPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "head_client_name",
    standart: false,
    visible: true,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];
export const REPORTS_CONSIGNMENT_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Verilmiş",
    dataIndex: "consignmentPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Geri alınmış",
    dataIndex: "returnedPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Satılmış",
    dataIndex: "soldPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dövrün sonuna qalıq",
    dataIndex: "remainedPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dövrün əvvəlinə qalıq",
    dataIndex: "beginningOfThePeriodRemainedPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "headContactName",
    standart: false,
    visible: true,
    fixed: false,
  },
];

export const Add_Multiple_Inv_Modal_Table_Data = [
  {
    name: "Tarix",
    dataIndex: "operationDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Biznes blok",
    dataIndex: "business_unit_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müqavilə",
    dataIndex: "contract_serial_number",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qalıq borc",
    dataIndex: "remainingInvoiceDebtWithCredit",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödəniləcək məbləğ",
    dataIndex: "mustPay",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödəniş statusu",
    dataIndex: "paymentStatus",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İcra statusu",
    dataIndex: "statusName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];
