export const PandL_ForDays_TABLE_SETTING_DATA = [
  {
    name: "Satışdan gəlir",
    dataIndex: 0,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Satışdan maya dəyəri",
    dataIndex: 1,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məcmu mənfəət (zərər)",
    dataIndex: 2,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməliyyat mənfəəti (zərəri)",
    dataIndex: 6,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Vergidən öncəki mənfəət (zərər)",
    dataIndex: 8,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Xalis mənfəət (zərər)",
    dataIndex: 10,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dəqiqləşdirişmiş xalis mənfəət (zərər)",
    dataIndex: 19,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İnzibati xərclər",
    dataIndex: 3,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməliyyat xəcləri",
    dataIndex: 4,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Digər xərclər",
    dataIndex: 5,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməkhaqqı fondu",
    dataIndex: 15,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Maliyyə xərcləri",
    dataIndex: 7,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Mənfəətdən vergilər xərci",
    dataIndex: 9,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Silinmiş mallar",
    dataIndex: 14,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Geri alınmış mallarda itirilmiş mənfəət",
    dataIndex: 16,
    standart: false,
    visible: false,
    fixed: false,
  },
];

export const PRODUCT_TABLE_SETTING_DATA = [
  {
    name: "Məhsul tipi",
    dataIndex: "isServiceType",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seriya nömrəsi",
    dataIndex: "isWithoutSerialNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kataloq",
    dataIndex: "parentCatalogName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Alt Kataloq",
    dataIndex: "catalogName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Şəkil",
    dataIndex: "attachmentName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məhsul adı",
    dataIndex: "name",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Bron sayı",
    dataIndex: "bronQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Konsiqnasiya sayı",
    dataIndex: "consignmentQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Cəmi say",
    dataIndex: "totalQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "idNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İstehsalçı",
    dataIndex: "manufacturerName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məhsul kodu",
    dataIndex: "productCode",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ölçü vahidi",
    dataIndex: "unitOfMeasurementName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Yol vergisi",
    dataIndex: "roadTax",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qiymət",
    dataIndex: "pricePerUnit",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Digər qiymət tipləri",
    dataIndex: "otherPrices",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Anbar sayı",
    dataIndex: "quantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Maya dəyəri (min)",
    dataIndex: "minPrice",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Maya dəyəri (max)",
    dataIndex: "maxPrice",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Maya dəyəri (orta)",
    dataIndex: "avgPrice",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Maya dəyəri (son)",
    dataIndex: "lastPrice",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstismar müddəti",
    dataIndex: "lifetime",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Minimal qalıq",
    dataIndex: "minimumStockQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Status",
    dataIndex: "isDeleted",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Etiket",
    dataIndex: "labels",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Planlama",
    dataIndex: "salesDraftQuantity",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Marka",
    dataIndex: "brandName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Barkod",
    dataIndex: "barcode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
];
