export const PandL_ForDays_TABLE_SETTING_DATA = [
  {
    name: "Satışdan gəlir",
    dataIndex: 0,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Satışdan maya dəyəri",
    dataIndex: 1,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məcmu mənfəət (zərər)",
    dataIndex: 2,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməliyyat mənfəəti (zərəri)",
    dataIndex: 6,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Vergidən öncəki mənfəət (zərər)",
    dataIndex: 8,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Xalis mənfəət (zərər)",
    dataIndex: 10,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dəqiqləşdirişmiş xalis mənfəət (zərər)",
    dataIndex: 19,
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İnzibati xərclər",
    dataIndex: 3,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməliyyat xəcləri",
    dataIndex: 4,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Digər xərclər",
    dataIndex: 5,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməkhaqqı fondu",
    dataIndex: 15,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Maliyyə xərcləri",
    dataIndex: 7,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Mənfəətdən vergilər xərci",
    dataIndex: 9,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Silinmiş mallar",
    dataIndex: 14,
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Geri alınmış mallarda itirilmiş mənfəət",
    dataIndex: 16,
    standart: false,
    visible: false,
    fixed: false,
  },
];
