export const Sales_Invoices_TABLE_SETTING_DATA = [
  {
    name: "Əməliyyat növü",
    dataIndex: "invoiceType",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İcra tarixi",
    dataIndex: "createdAt",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməliyyat tarixi",
    dataIndex: "operationDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qarşı tərəf",
    dataIndex: "counterparty",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ödəniş tarixi",
    dataIndex: "firstOpenCreditDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müqavilə",
    dataIndex: "contractNo",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ödəniş statusu",
    dataIndex: "paymentStatus",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son qiymət",
    dataIndex: "endPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son qiymət (Əsas valyuta)",
    dataIndex: "endPriceInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Biznes blok",
    dataIndex: "businessUnitId",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Menecer",
    dataIndex: "salesmanName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "counterpartyHeadContactName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Yol vergisi",
    dataIndex: "totalRoadTaxAmount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İcra statusu",
    dataIndex: "statusName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Status",
    dataIndex: "statusOfOperationLabel",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məbləğ",
    dataIndex: "amount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Gecikmə (gün)",
    dataIndex: "daysFromLastPaymentDate",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Xərc məbləği",
    dataIndex: "totalPaymentsAmountConvertedToMainCurrency",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməkhaqqı",
    dataIndex: "totalSalariesAmountConvertedToMainCurrency",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Silinmiş mallar",
    dataIndex: "totalRemoveInvoicesAmountConvertedToMainCurrency",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə olunub",
    dataIndex: "operatorName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Anbar",
    dataIndex: "stockName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ödənilməlidir",
    dataIndex: "endPriceCache",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Endirim (%)",
    dataIndex: "discountPercentage",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Endirim",
    dataIndex: "discountAmount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul miqdarı",
    dataIndex: "totalQuantity",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Vergi (%)",
    dataIndex: "taxPercentage",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Vergi",
    dataIndex: "taxAmount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Yekun ƏDV ilə",
    dataIndex: "endPriceAmountWithTax",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Agent",
    dataIndex: "agentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "counterpartyType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "counterpartyCategoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "counterpartyPhoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "counterpartyEmails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "counterpartyId",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "counterpartyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "counterpartyWebsites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "counterpartyAddress",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "counterpartyPriceType",
    standart: false,
    visible: false,
    fixed: false,
  },

  {
    name: "Əlavə məlumat (Əlaqə)",
    dataIndex: "counterpartyDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  // {
  //     name: 'Menecer(Əlaqə)',
  //     dataIndex: '',
  //     standart: false,
  //     visible: false,
  //     fixed: false,
  // },
  {
    name: "Şirkət adı",
    dataIndex: "counterpartyOfficialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "counterpartyGeneralDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "counterpartyCompanyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "counterpartyBankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "counterpartyBankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "counterpartyBankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "counterpartyCorrespondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "counterpartySettlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "counterpartySwift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Yazışma",
    dataIndex: "comments",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const Sales_SoldItems_TABLE_SETTING_DATA = (
  sales_sold_items_cost,
  sales_sold_items_cost_main,
  sales_sold_items_cost_main_total,
  sales_sold_items_margin
) => [
  {
    name: "Anbar",
    dataIndex: "warehouseName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Kataloq",
    dataIndex: "rootCatalogName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Alt kataloq",
    dataIndex: "catalogName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məhsul",
    dataIndex: "productName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Say",
    dataIndex: "quantity",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ölçü vahidi",
    dataIndex: "unitOfmeasuring",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Vahidin qiyməti",
    dataIndex: "pricePerUnitInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Toplam qiymət",
    dataIndex: "totalPriceInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Endirim",
    dataIndex: "discountAmountPerUnit",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Endirim(%)",
    dataIndex: "discountAmountPerUnitPercentage",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son qiymət",
    dataIndex: "endPricePerUnitInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "headClientName",
    standart: false,
    visible: true,
    fixed: false,
  },
  {
    name: "Vahidin son qiyməti",
    dataIndex: "endPricePerUnitInMainCurrencyUnit",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Vahidin maya dəyəri",
    dataIndex: "costPerUnitInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_sold_items_cost === 2,
  },
  {
    name: "Maya dəyəri",
    dataIndex: "costOfGoodsSoldInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_sold_items_cost_main === 2,
  },
  {
    name: "Mənfəət",
    dataIndex: "endPricePerUnitInMainCurrencyProfit",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_sold_items_cost_main_total === 2,
  },
  {
    name: "Marja",
    dataIndex: "endPricePerUnitInMainCurrencyMargin",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_sold_items_margin === 2,
  },
  {
    name: "Tarix",
    dataIndex: "operationDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müqavilə",
    dataIndex: "contractSerialNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Alıcı",
    dataIndex: "clientName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Menecer",
    dataIndex: "salesman",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Agent",
    dataIndex: "agent",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməliyyatçı",
    dataIndex: "operator",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul tipi",
    dataIndex: "isServiceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seriya nömrəsi",
    dataIndex: "isWithoutSerialNumber",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Barkod",
    dataIndex: "barcode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şəkil",
    dataIndex: "attachmentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstehsalçı",
    dataIndex: "manufacturerName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul kodu",
    dataIndex: "productCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Satış qiyməti",
    dataIndex: "pricePerUnit",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Marka",
    dataIndex: "brandName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat (məhsul)",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat (qaimə)",
    dataIndex: "invoiceDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const Sales_Purchased_TABLE_SETTING_DATA = (
  sales_purchased_items_price_per_item,
  sales_purchased_items_total_price,
  sales_purchased_items_discount,
  sales_purchased_items_endprice,
  sales_purchased_items_per_item_endprice,
  sales_purchased_items_main_currency
) => [
  {
    name: "Anbar",
    dataIndex: "warehouseName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Kataloq",
    dataIndex: "rootCatalogName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Alt kataloq",
    dataIndex: "catalogName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məhsul adı",
    dataIndex: "productName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Say",
    dataIndex: "quantity",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ölçü vahidi",
    dataIndex: "unitOfmeasuring",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Vahidin qiyməti",
    dataIndex: "costPerUnit",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_purchased_items_price_per_item === 2,
  },
  {
    name: "Toplam qiymət",
    dataIndex: "totalCost",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_purchased_items_total_price === 2,
  },
  {
    name: "Endirim (%)",
    dataIndex: "discountAmountPerUnit",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_purchased_items_discount === 2,
  },
  {
    name: "Son qiymət",
    dataIndex: "endPricePerUnit",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_purchased_items_endprice === 2,
  },
  {
    name: "Vahidin son qiyməti",
    dataIndex: "endPricePerUnitInMainCurrencyUnit",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_purchased_items_per_item_endprice === 2,
  },
  {
    name: "Əsas valyuta",
    dataIndex: "endPriceInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
    hasPermission: sales_purchased_items_main_currency === 2,
  },
  {
    name: "Tarix",
    dataIndex: "operationDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müqavilə",
    dataIndex: "contractNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Təchizatçı",
    dataIndex: "supplier",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Agent",
    dataIndex: "agent",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "headSupplierName",
    standart: false,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməliyyatçı",
    dataIndex: "operator",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul tipi",
    dataIndex: "isServiceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seriya nömrəsi",
    dataIndex: "isWithoutSerialNumber",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Barkod",
    dataIndex: "barcode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şəkil",
    dataIndex: "attachmentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstehsalçı",
    dataIndex: "manufacturerName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul kodu",
    dataIndex: "productCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Satış qiyməti",
    dataIndex: "pricePerUnit",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Marka",
    dataIndex: "brandName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat (məhsul)",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat (qaimə)",
    dataIndex: "invoiceDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];
export const Sales_GoodTurnovers_TABLE_SETTING_DATA = [
  {
    name: "Anbar",
    dataIndex: "stock_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "catalog_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Alt kateqoriya",
    dataIndex: "subcatalog_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məhsul",
    dataIndex: "product_name",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ölçü vahidi",
    dataIndex: "unit_of_measurement_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dövrün əvvəlinə",
    dataIndex: "start_of_period",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Daxil olma",
    dataIndex: "income",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Xaric olma",
    dataIndex: "outgo",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dövrün sonuna",
    dataIndex: "endOfPeriod",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Məhsul tipi",
    dataIndex: "isServiceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seriya nömrəsi",
    dataIndex: "isWithoutSerialNumber",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Barkod",
    dataIndex: "barcode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Marka",
    dataIndex: "brand_name",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "product_id",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şəkil",
    dataIndex: "attachmentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstehsalçı",
    dataIndex: "manufacturerName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul kodu",
    dataIndex: "productCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Satış qiyməti",
    dataIndex: "pricePerUnit",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const Sales_Contracts_TABLE_SETTING_DATA = [
  {
    name: "Qarşı tərəf",
    dataIndex: "counterparty_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müqavilə",
    dataIndex: "contract_no",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Sənəd",
    dataIndex: "document",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məsul şəxs",
    dataIndex: "responsible_person_name",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Başlama tarixi",
    dataIndex: "start_date",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Bitmə tarixi",
    dataIndex: "end_date",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Günlərin sayı",
    dataIndex: "days_to_end",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məbləğ",
    dataIndex: "amount",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Dövriyyə",
    dataIndex: "turnover",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qalıq",
    dataIndex: "rest",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Status",
    dataIndex: "status",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İcra statusu",
    dataIndex: "statusName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Valyuta",
    dataIndex: "currencycode",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Növ",
    dataIndex: "contract_type",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstiqamət",
    dataIndex: "direction",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqəli tərəflər",
    dataIndex: "related_contacts",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Biznes blok",
    dataIndex: "business_unit_id",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "counterpartyType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "counterpartyCategoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "counterpartyPhoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "counterpartyEmails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer (Əlaqə)",
    dataIndex: "counterpartyManager",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "counterpartyId",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "counterpartyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "counterpartyWebsites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "counterpartyAddress",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "counterpartyPriceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat (Əlaqə)",
    dataIndex: "counterpartyDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "counterpartyOfficialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "counterpartyGeneralDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "counterpartyCompanyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "counterpartyBankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "counterpartyBankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "counterpartyBankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "counterpartyCorrespondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "counterpartySettlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "counterpartySwift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Yazışma",
    dataIndex: "comments",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const Sales_Contracts_Addition_TABLE_SETTING_DATA = [
  {
    name: "Məhsul adı",
    dataIndex: "customProductName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Qiymət",
    dataIndex: "invoicePrice",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Say",
    dataIndex: "quantity",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ölçü vahidi",
    dataIndex: "unitOfMeasurements",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Toplam",
    dataIndex: "total",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Açıqlama",
    dataIndex: "explanation",
    standart: false,
    visible: false,
    fixed: false,
  },
];

export const Production_Removed_Products_TABLE_SETTING_DATA = [
  {
    name: "Məhsul adı",
    dataIndex: "productName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Say",
    dataIndex: "quantity",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Qaimə sayı ",
    dataIndex: "invoiceNumbers",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Cəmi maya dəyəri",
    dataIndex: "totalEndPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Maya dəyəri",
    dataIndex: "pricePerUnit",
    standart: true,
    visible: true,
    fixed: false,
  },
  // {
  //     name: 'Anbar qalığı',
  //     dataIndex: 'quantityInStock',
  //     standart: true,
  //     visible: true,
  //     fixed: false,
  // },
  {
    name: "Ölçü vahidi",
    dataIndex: "unitOfMeasurementName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seriya nömrəsi",
    dataIndex: "serialNumbers",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kataloq",
    dataIndex: "rootCatalogName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Alt kataloq",
    dataIndex: "catalogName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Barkod",
    dataIndex: "barcode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şəkil",
    dataIndex: "attachmentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstehsalçı",
    dataIndex: "manufacturerName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul kodu",
    dataIndex: "product_code",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
];

export const Contract_Detail_Removed_Products_TABLE_SETTING_DATA = [
  {
    name: "Məhsul adı",
    dataIndex: "productName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumbers",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Say",
    dataIndex: "quantity",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Ölçü vahidi",
    dataIndex: "unitOfMeasurementName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seriya nömrəsi",
    dataIndex: "serialNumbers",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kataloq",
    dataIndex: "rootCatalogName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Alt kataloq",
    dataIndex: "catalogName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Barkod",
    dataIndex: "barcode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şəkil",
    dataIndex: "attachmentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstehsalçı",
    dataIndex: "manufacturerName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul kodu",
    dataIndex: "product_code",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
];

export const Contract_Detail_Invoice_Products_TABLE_SETTING_DATA = [
  {
    name: "Məhsul adı",
    dataIndex: "productName",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumbers",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Say",
    dataIndex: "quantity",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Daxil olma",
    dataIndex: "rootInvoiceNumbers",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Ölçü vahidi",
    dataIndex: "unitOfMeasurementName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seriya nömrəsi",
    dataIndex: "serialNumbers",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Kataloq",
    dataIndex: "rootCatalogName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Alt kataloq",
    dataIndex: "catalogName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Barkod",
    dataIndex: "barcode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şəkil",
    dataIndex: "attachmentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İstehsalçı",
    dataIndex: "manufacturerName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul kodu",
    dataIndex: "product_code",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
];

export const getByFilter = (filter) => {
  switch (filter) {
    case "contact":
      return [
        {
          name: "Qarşı tərəf",
          dataIndex: "counterpartyName",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Müqavilə sayı",
          dataIndex: "contract_quantity",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Məhsul sayı (Əlavə)",
          dataIndex: "customProductName_quantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Təhvil verilməlidir, say",
          dataIndex: "quantity",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Təhvil verilib, say",
          dataIndex: "salesQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Geri alınıb, say",
          dataIndex: "returnFromCustomerQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Qalıb, say",
          dataIndex: "remainingQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Təyin olunmayıb, say",
          dataIndex: "availableQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Əlaqə tipi",
          dataIndex: "type",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Kateqoriya",
          dataIndex: "categoryIds",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlaqə tel",
          dataIndex: "phoneNumbers",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Email",
          dataIndex: "emails",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Menecer",
          dataIndex: "manager",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "ID nömrə",
          dataIndex: "id",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN",
          dataIndex: "voen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Websayt",
          dataIndex: "websites",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Ünvan",
          dataIndex: "address",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Qiymət tipi",
          dataIndex: "priceType",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlavə məlumat",
          dataIndex: "description",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Şirkət adı",
          dataIndex: "officialName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Baş direktor",
          dataIndex: "generalDirector",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN (Şirkət)",
          dataIndex: "companyVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Bank adı",
          dataIndex: "bankName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN (Bank)",
          dataIndex: "bankVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Kod",
          dataIndex: "bankCode",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Müxbir hesab (M/h)",
          dataIndex: "correspondentAccount",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Hesablaşma hesabı (H/h)",
          dataIndex: "settlementAccount",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "S.W.I.F.T.",
          dataIndex: "swift",
          standart: false,
          visible: false,
          fixed: false,
        },
      ];
    case "contract":
      return [
        {
          name: "Müqavilə",
          dataIndex: "contract_no",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Qarşı tərəf",
          dataIndex: "counterpartyName",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Məhsul sayı (Əlavə)",
          dataIndex: "customProductName_quantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Təhvil verilməlidir, say",
          dataIndex: "quantity",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Təhvil verilib, say",
          dataIndex: "salesQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Geri alınıb, say",
          dataIndex: "returnFromCustomerQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Qalıb, say",
          dataIndex: "remainingQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Təyin olunmayıb, say",
          dataIndex: "availableQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Biznes blok",
          dataIndex: "businessUnitName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlaqə tipi",
          dataIndex: "counterpartyType",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Kateqoriya",
          dataIndex: "counterpartyCategoryIds",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlaqə tel",
          dataIndex: "counterpartyPhoneNumbers",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Email",
          dataIndex: "counterpartyEmails",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Menecer (Əlaqə)",
          dataIndex: "counterpartyManager",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "ID nömrə",
          dataIndex: "counterpartyId",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN",
          dataIndex: "counterpartyVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Websayt",
          dataIndex: "counterpartyWebsites",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Ünvan",
          dataIndex: "counterpartyAddress",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Qiymət tipi",
          dataIndex: "counterpartyPriceType",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlavə məlumat (Əlaqə)",
          dataIndex: "counterpartyDescription",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Şirkət adı",
          dataIndex: "counterpartyOfficialName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Baş direktor",
          dataIndex: "counterpartyGeneralDirector",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN (Şirkət)",
          dataIndex: "counterpartyCompanyVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Bank adı",
          dataIndex: "counterpartyBankName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN (Bank)",
          dataIndex: "counterpartyBankVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Kod",
          dataIndex: "counterpartyBankCode",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Müxbir hesab (M/h)",
          dataIndex: "counterpartyCorrespondentAccount",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Hesablaşma hesabı (H/h)",
          dataIndex: "counterpartySettlementAccount",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "S.W.I.F.T.",
          dataIndex: "counterpartySwift",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Seç",
          dataIndex: "actions",
          standart: true,
          visible: true,
          fixed: false,
        },
      ];
    case "product":
      return [
        {
          name: "Məhsul adı (Əlavə)",
          dataIndex: "customProductName",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Müqavilə sayı",
          dataIndex: "contract_quantity",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Təhvil verilməlidir, say",
          dataIndex: "quantity",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Təhvil verilib, say",
          dataIndex: "salesQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Geri alınıb, say",
          dataIndex: "returnFromCustomerQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Qalıb, say",
          dataIndex: "remainingQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Təyin olunmayıb, say",
          dataIndex: "availableQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
      ];
    default:
      return [
        {
          name: "Qarşı tərəf",
          dataIndex: "counterpartyName",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Müqavilə",
          dataIndex: "contract_no",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Məhsul adı (Əlavə)",
          dataIndex: "customProductName",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Məhsul adı (Kataloq)",
          dataIndex: "productName",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Təhvil verilməlidir, say",
          dataIndex: "quantity",
          standart: true,
          visible: true,
          fixed: true,
        },
        {
          name: "Təhvil verilib, say",
          dataIndex: "salesQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Geri alınıb, say",
          dataIndex: "returnFromCustomerQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Qalıb, say",
          dataIndex: "remainingQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Son icra tarixi",
          dataIndex: "lastExecutionDate",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Təyin olunmayıb, say",
          dataIndex: "availableQuantity",
          standart: true,
          visible: true,
          fixed: false,
        },
        {
          name: "Anbar qalığı, say",
          dataIndex: "quantityInStock",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "İcra müddəti",
          dataIndex: "executionDate",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Status",
          dataIndex: "status",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Biznes blok",
          dataIndex: "businessUnitName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Ölçü vahidi",
          dataIndex: "productUnitOfMeasurement",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Kataloq",
          dataIndex: "parentCatalog",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Alt kataloq",
          dataIndex: "catalog",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Növ",
          dataIndex: "contractType",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Məsul şəxs",
          dataIndex: "responsiblePersonName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Başlama tarixi",
          dataIndex: "contractStartDate",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Bitmə tarixi",
          dataIndex: "contractEndDate",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Sifariş",
          dataIndex: "orders",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlaqə tipi",
          dataIndex: "counterpartyType",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Kateqoriya",
          dataIndex: "counterpartyCategoryIds",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlaqə tel",
          dataIndex: "counterpartyPhoneNumbers",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Email",
          dataIndex: "counterpartyEmails",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Menecer (Əlaqə)",
          dataIndex: "counterpartyManager",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "ID nömrə",
          dataIndex: "counterpartyId",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN",
          dataIndex: "counterpartyVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Websayt",
          dataIndex: "counterpartyWebsites",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Ünvan",
          dataIndex: "counterpartyAddress",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Qiymət tipi",
          dataIndex: "counterpartyPriceType",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Əlavə məlumat (Əlaqə)",
          dataIndex: "counterpartyDescription",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Şirkət adı",
          dataIndex: "counterpartyOfficialName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Baş direktor",
          dataIndex: "counterpartyGeneralDirector",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN (Şirkət)",
          dataIndex: "counterpartyCompanyVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Bank adı",
          dataIndex: "counterpartyBankName",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "VÖEN (Bank)",
          dataIndex: "counterpartyBankVoen",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Kod",
          dataIndex: "counterpartyBankCode",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Müxbir hesab (M/h)",
          dataIndex: "counterpartyCorrespondentAccount",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "Hesablaşma hesabı (H/h)",
          dataIndex: "counterpartySettlementAccount",
          standart: false,
          visible: false,
          fixed: false,
        },
        {
          name: "S.W.I.F.T.",
          dataIndex: "counterpartySwift",
          standart: false,
          visible: false,
          fixed: false,
        },
      ];
  }
};

export const Sales_Production_TABLE_SETTING_DATA = [
  {
    name: "İcra tarixi",
    dataIndex: "createdAt",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Sifarişçi",
    dataIndex: "clientId",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Sənəd",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "İstehsalat",
    dataIndex: "customInvoiceNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Planlaşdırılmış satış qiyməti",
    dataIndex: "planned_price",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Planlaşdırılmış maya dəyəri",
    dataIndex: "planned_cost",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Anbara göndərilib",
    dataIndex: "transferredInvoiceProductsTotalQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İstehsal sayı",
    dataIndex: "productionInvoiceQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qalıb",
    dataIndex: "remainproductionInvoiceQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Satılıb",
    dataIndex: "soldQuantity",
    standart: true,
    visible: false,
    fixed: false,
  },
  {
    name: "Faktiki maya dəyəri",
    dataIndex: "cost",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Yayınma",
    dataIndex: "planned_cost_deviation",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Yayınma %",
    dataIndex: "planned_cost_percentage",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məhsul miqdarı",
    dataIndex: "totalQuantity",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Biznes blok",
    dataIndex: "businessUnitId",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müddət/Cari müddət (gün)",
    dataIndex: "CurrentDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Status",
    dataIndex: "status",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Sifariş məbləği (Əsas valyuta)",
    dataIndex: "endPriceInMainCurrency",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Başlama tarixi",
    dataIndex: "startDate",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bitmə tarixi",
    dataIndex: "endDate",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Gecikmə, gün",
    dataIndex: "daysPassed",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Menecer",
    dataIndex: "salesmanName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "İcra statusu",
    dataIndex: "statusName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müqavilə",
    dataIndex: "contractNo",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Materiallar anbarı",
    dataIndex: "productionMaterialsStockName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "counterpartyType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "counterpartyCategoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tel",
    dataIndex: "counterpartyPhoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "counterpartyEmails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "counterpartyId",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "counterpartyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "counterpartyWebsites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "counterpartyAddress",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "counterpartyPriceType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Şirkət adı",
    dataIndex: "counterpartyOfficialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "counterpartyGeneralDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "counterpartyCompanyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "counterpartyBankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "counterpartyBankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "counterpartyBankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "counterpartyCorrespondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "counterpartySettlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "counterpartySwift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Yazışma",
    dataIndex: "comments",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];

export const SALES_TEMPLATE_TABLE_SETTING_DATA = [
  {
    name: "Əməliyyat növü",
    dataIndex: "invoiceType",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "İcra tarixi",
    dataIndex: "createdAt",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Əməliyyat tarixi",
    dataIndex: "operationDate",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Sənəd adı",
    dataIndex: "customInvoiceNumber",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qarşı tərəf",
    dataIndex: "counterparty",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Müqavilə",
    dataIndex: "contractNo",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Qaimə",
    dataIndex: "invoiceNumber",
    standart: true,
    visible: true,
    fixed: true,
  },
  {
    name: "Son qiymət",
    dataIndex: "endPrice",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Son qiymət (Əsas valyuta)",
    dataIndex: "endPriceInMainCurrency",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Biznes blok",
    dataIndex: "businessUnitId",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Menecer",
    dataIndex: "salesmanName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Baş əlaqə",
    dataIndex: "counterpartyHeadContactName",
    standart: false,
    visible: true,
    fixed: false,
  },
  {
    name: "İcra statusu",
    dataIndex: "statusName",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Status",
    dataIndex: "statusOfOperationLabel",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Məbləğ",
    dataIndex: "amount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Xərc məbləği",
    dataIndex: "totalPaymentsAmountConvertedToMainCurrency",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əməkhaqqı",
    dataIndex: "totalSalariesAmountConvertedToMainCurrency",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Silinmiş mallar",
    dataIndex: "totalRemoveInvoicesAmountConvertedToMainCurrency",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə olunub",
    dataIndex: "operatorName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Anbar",
    dataIndex: "stockName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Endirim (%)",
    dataIndex: "discountPercentage",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Endirim",
    dataIndex: "discountAmount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Vahidin çəkisi, kg",
    dataIndex: "weightPerUnit",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Vahidin həcmi, m3",
    dataIndex: "volumePerUnit",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ümumi çəki, kg",
    dataIndex: "totalWeight",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ümumi həcm, m3",
    dataIndex: "totalVolume",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Məhsul miqdarı",
    dataIndex: "totalQuantity",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Vergi (%)",
    dataIndex: "taxPercentage",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Vergi",
    dataIndex: "taxAmount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Yekun ƏDV ilə",
    dataIndex: "endPriceAmountWithTax",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Agent",
    dataIndex: "agentName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlavə məlumat",
    dataIndex: "description",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Əlaqə tipi",
    dataIndex: "counterpartyType",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kateqoriya",
    dataIndex: "counterpartyCategoryIds",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Telefon",
    dataIndex: "counterpartyPhoneNumbers",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Email",
    dataIndex: "counterpartyEmails",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "ID nömrə",
    dataIndex: "counterpartyId",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN",
    dataIndex: "counterpartyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Websayt",
    dataIndex: "counterpartyWebsites",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Ünvan",
    dataIndex: "counterpartyAddress",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Qiymət tipi",
    dataIndex: "counterpartyPriceType",
    standart: false,
    visible: false,
    fixed: false,
  },

  {
    name: "Əlavə məlumat (Əlaqə)",
    dataIndex: "counterpartyDescription",
    standart: false,
    visible: false,
    fixed: false,
  },
  // {
  //     name: 'Menecer(Əlaqə)',
  //     dataIndex: '',
  //     standart: false,
  //     visible: false,
  //     fixed: false,
  // },
  {
    name: "Şirkət adı",
    dataIndex: "counterpartyOfficialName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Baş direktor",
    dataIndex: "counterpartyGeneralDirector",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Şirkət)",
    dataIndex: "counterpartyCompanyVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Bank adı",
    dataIndex: "counterpartyBankName",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "VÖEN (Bank)",
    dataIndex: "counterpartyBankVoen",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Kod",
    dataIndex: "counterpartyBankCode",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Müxbir hesab (M/h)",
    dataIndex: "counterpartyCorrespondentAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Hesablaşma hesabı (H/h)",
    dataIndex: "counterpartySettlementAccount",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "S.W.I.F.T.",
    dataIndex: "counterpartySwift",
    standart: false,
    visible: false,
    fixed: false,
  },
  {
    name: "Yazışma",
    dataIndex: "comments",
    standart: true,
    visible: true,
    fixed: false,
  },
  {
    name: "Seç",
    dataIndex: "actions",
    standart: true,
    visible: true,
    fixed: false,
  },
];
